### ISSUE TITLE
notificaciones-funcionalidad

### ISSUE THREAD

**Issue by gamanox** [we-the-force/wtf-doctorize-pwa#148]
Vamos a integrar en el frontend el servicio de notificaciones push web Onesignal para que sea más rápida la implementación en el backend. Tenemos un detalle actualmente, falta unificar los dos serviceworkers, el de l app de doctorize y el de las notificaciones de onesignal, Ale lo va a resolver.

### Accesos
https://app.onesignal.com/
user: will@wetheforce.com
pass: q1w2e3r4

### Documentación
https://documentation.onesignal.com/docs/web-push-quickstart

**Comment by srlechuga18** [comment]
Notificaciones

1. Doctor

- se ha modificado tu perfil
- Se registró su cuenta, confirmar
- Invitación al asistente aceptada
- cita de paciente confirmada
- próximo evento en la agenda 
- se ha recibido un pago
- petición de cambio de contraseña realizada, verificar correo

consultorio

- consultorio creado con éxito ?
- error al crear consultorio ?
- consultorio editado con éxito ?
- eliminado ?

asistente

- invitación enviada al asistente ?
- configuración del asistente realizada ? 
- error al enviar invitación  ?
- eliminado ?

paciente

- agregado ?
- modificado ?
- eliminado ?
- error ?

consulta

- agregado ?
- modificado ?
- cita
- creada ?
- cancelada ?
- re-agendada ?

2. Paciente
- recordar de la cita
